name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: target nodejs env
        uses: actions/setup-node@v3
        with:
          node-version: '14'
          
      - name: cd ./dev
        run:
          cd ./dev

      - name: install
        run:
          npm i

      - name: build
        run:
          npm run content:build
          
      - name: done  
        run:
          echo done.
          
      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dist-without-markdown
          path: ./dev/content/.vuepress/dist
