name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: enter dev workspace
        run:
          cd ./dev
      - name: target nodejs env
        uses: actions/setup-node@v3
        with:
          node-version: '14'
          cache: 'npm'
      - name: build project to local
        run:
          echo will build the project
          npm i
          npm run content:build
          echo done.
      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dist-without-markdown
          path: ./dev/content/.vuepress/dist
