name: CI

on: [push, pull_request]
#
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: build project to local
        run:
          echo will build the project.
#          npm run content:build
          cp -R ./docs/ ./
          echo done.
