name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: build project to local
        run:
          echo build project.
          npm run example:build
          cp -R ./example/.vuepress/dist ./
          echo done.
